# Generated by Django 3.0.7 on 2020-06-21 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.AddField(
            model_name='video',
            name='v_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='youtube 영상 코드를 입력해주세요', max_length=140),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
