# Generated by Django 3.0.7 on 2020-06-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='workingout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeT.WorkOutCategory'),
        ),
    ]
