# Generated by Django 3.0.7 on 2020-06-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeT', '0002_auto_20200622_0158'),
        ('homeT', '0002_comment'),
    ]

    operations = [
    ]
