# Generated by Django 3.0.7 on 2020-06-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeT', '0003_merge_20200622_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
