# Generated by Django 3.0.7 on 2020-06-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeT', '0004_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeT.Video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='homeT.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
