# Generated by Django 3.0.7 on 2020-06-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeT', '0004_auto_20200624_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='tagcontent',
            field=models.CharField(default=django.utils.timezone.now, help_text='관련 태그를 최대 140자 입력 가능', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='homeT.Tag'),
        ),
    ]
