# Generated by Django 3.0.7 on 2020-06-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeT', '0007_auto_20200624_1842'),
        ('homeT', '0007_auto_20200624_2006'),
    ]

    operations = [
    ]
